/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import conexao.ConexaoException;
import exception.ExcecaoComposta;
import exception.NaoHaClientesCadastrados;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import manager.Gerenciador;

/**
 *
 * @author Admin
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    Gerenciador gerenciador;
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal(Gerenciador gerenciador) {
        initComponents();
        
        this.gerenciador = gerenciador;
    }

    private void trocarPainel(JPanel painel){
        painelPrincipal.removeAll();
        painelPrincipal.add(painel, "painel");
        java.awt.CardLayout painelPrincipalLayout = (java.awt.CardLayout)(painelPrincipal.getLayout());
        painelPrincipalLayout.show(painelPrincipal, "painel");
        
        pack();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        depositoMnIt = new javax.swing.JMenuItem();
        clienteMnIt = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        vendaCadastrarBt = new javax.swing.JMenuItem();
        buscarDataBt = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setLayout(new java.awt.CardLayout());

        jMenu1.setText("Iniciar");

        depositoMnIt.setText("Depósito");
        depositoMnIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoMnItActionPerformed(evt);
            }
        });
        jMenu1.add(depositoMnIt);

        clienteMnIt.setText("Cliente");
        clienteMnIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteMnItActionPerformed(evt);
            }
        });
        jMenu1.add(clienteMnIt);

        jMenu2.setText("Venda");

        vendaCadastrarBt.setText("Cadastrar");
        vendaCadastrarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaCadastrarBtActionPerformed(evt);
            }
        });
        jMenu2.add(vendaCadastrarBt);

        buscarDataBt.setText("Buscar por data");
        buscarDataBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDataBtActionPerformed(evt);
            }
        });
        jMenu2.add(buscarDataBt);

        jMenu1.add(jMenu2);

        jMenu3.setText("Produto");

        jMenuItem1.setText("Cadastrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Alterar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteMnItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteMnItActionPerformed
        try {
            // TODO add your handling code here:
            trocarPainel(new ClientePainel(gerenciador));
        } catch (ConexaoException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clienteMnItActionPerformed

    private void depositoMnItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoMnItActionPerformed
        // TODO add your handling code here:
        trocarPainel(new DepositoPainel(gerenciador));
    }//GEN-LAST:event_depositoMnItActionPerformed

    private void buscarDataBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDataBtActionPerformed
        // TODO add your handling code here:
        trocarPainel(new VendaBuscarData(gerenciador));
    }//GEN-LAST:event_buscarDataBtActionPerformed

    private void vendaCadastrarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaCadastrarBtActionPerformed
        try {
            // TODO add your handling code here:
            try{
                vendaCadastrarBtActionPerformedOrFail(evt);
            }catch(ExcecaoComposta exComp){
                exComp.exibirJanela(this);
            }
        } catch (ConexaoException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vendaCadastrarBtActionPerformed

    private void vendaCadastrarBtActionPerformedOrFail(java.awt.event.ActionEvent evt) throws ConexaoException, ExcecaoComposta {                                                 
        if(gerenciador.clientesBuscarTodos() == null || gerenciador.clientesBuscarTodos().size() < 1){
            ExcecaoComposta exComp = new ExcecaoComposta();
            exComp.excecaoAdicionar(new NaoHaClientesCadastrados());
            
            throw exComp;
        }
        trocarPainel(new VendaPainel(gerenciador));
    }
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            trocarPainel(new ProdutoPainel(gerenciador));
        } catch (ConexaoException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
            // TODO add your handling code here:
            trocarPainel(new ProdutoAlterar(gerenciador));
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buscarDataBt;
    private javax.swing.JMenuItem clienteMnIt;
    private javax.swing.JMenuItem depositoMnIt;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JMenuItem vendaCadastrarBt;
    // End of variables declaration//GEN-END:variables
}
