/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import conexao.ConexaoException;
import manager.Gerenciador;
import entity.Deposito;
import entity.DepositoProduto;
import entity.Produto;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ProdutoPainel extends javax.swing.JPanel {
    Gerenciador gerenciador;
    List<Deposito> depositos;
    /**
     * Creates new form Produto
     */
    public ProdutoPainel(Gerenciador gerenciador) throws ConexaoException {
        initComponents();
        
        this.gerenciador = gerenciador;
        
        gerenciador.produtoIniciar();
        
        depositos = gerenciador.depositosBuscarTodos();
        
        for(Deposito deposito : depositos){
            depositosCmbBx.addItem(deposito);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        depositosTbl = new javax.swing.JTable();
        quantidadeSpn = new javax.swing.JSpinner();
        nomeTxtFld = new javax.swing.JTextField();
        precoFmtTxtFld = new javax.swing.JFormattedTextField();
        cadastrarBt = new javax.swing.JButton();
        depositosCmbBx = new javax.swing.JComboBox<>();
        adicionarDepositoBT = new javax.swing.JButton();

        jLabel1.setText("Nome: ");

        jLabel2.setText("Preço: ");

        jLabel3.setText("Quantidade: ");

        jLabel4.setText("Depósitos");

        depositosTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Rua"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(depositosTbl);

        precoFmtTxtFld.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        cadastrarBt.setText("Cadastrar");
        cadastrarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtActionPerformed(evt);
            }
        });

        adicionarDepositoBT.setText("Adicionar");
        adicionarDepositoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarDepositoBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeTxtFld))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precoFmtTxtFld))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantidadeSpn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(adicionarDepositoBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depositosCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadastrarBt)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(precoFmtTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantidadeSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(depositosCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adicionarDepositoBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarBt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtActionPerformed
        try {
            // TODO add your handling code here:
            gerenciador.produtoSetNome(nomeTxtFld.getText());
            gerenciador.produtoSetQuantidade((Integer) quantidadeSpn.getValue());
            gerenciador.produtoSetPreco((Double) precoFmtTxtFld.getValue());
            
            gerenciador.produtoConcluir();
        } catch (ConexaoException ex) {
            Logger.getLogger(ProdutoPainel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cadastrarBtActionPerformed

    private void adicionarDepositoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarDepositoBTActionPerformed
        // TODO add your handling code here:
        Deposito deposito = (Deposito) depositosCmbBx.getSelectedItem();
        gerenciador.produtoAddDepositoProduto(deposito);
        atualizarTabela();
    }//GEN-LAST:event_adicionarDepositoBTActionPerformed

    private void atualizarTabela(){
        DefaultTableModel model = (DefaultTableModel) depositosTbl.getModel();
        model.setRowCount(0);
 
        for(DepositoProduto depositoProduto : gerenciador.getProdutoNovoDepositoProdutos()){
            model.addRow(new Object[]{
                    depositoProduto.getDeposito().getNome(),
                    depositoProduto.getDeposito().getEndereco()
            });
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarDepositoBT;
    private javax.swing.JButton cadastrarBt;
    private javax.swing.JComboBox<Deposito> depositosCmbBx;
    private javax.swing.JTable depositosTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeTxtFld;
    private javax.swing.JFormattedTextField precoFmtTxtFld;
    private javax.swing.JSpinner quantidadeSpn;
    // End of variables declaration//GEN-END:variables

    void tabelaBuscarTodos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
