/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import conexao.ConexaoException;
import entity.Venda;
import java.awt.Point;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import manager.Gerenciador;

/**
 *
 * @author Admin
 */
public class VendaBuscarData extends javax.swing.JPanel {
    Gerenciador gerenciador;
    List<Venda> vendas;
    /**
     * Creates new form VendaBuscarData
     */
    public VendaBuscarData(Gerenciador gerenciador) {
        initComponents();
        
        this.gerenciador = gerenciador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataInicioJCld = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        dataFinalJCld = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        pesquisarBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vendaTbl = new javax.swing.JTable();

        jLabel1.setText("Data inicio: ");

        jLabel2.setText("Data final: ");

        pesquisarBt.setText("Pesquisar");
        pesquisarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarBtActionPerformed(evt);
            }
        });

        vendaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Forma de pagamento", "Subtotal soma", "Valor total", "Data", "Dias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vendaTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                vendaTblMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(vendaTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dataFinalJCld, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(dataInicioJCld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pesquisarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(dataInicioJCld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataFinalJCld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(pesquisarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarBtActionPerformed
        // TODO add your handling code here:
        try {
            vendas = gerenciador.vendaBuscarPorData(dataInicioJCld.getDate(), dataFinalJCld.getDate());

            DefaultTableModel model = (DefaultTableModel) vendaTbl.getModel();
            model.setRowCount(0);

            for(Venda venda : vendas){
                model.addRow(new Object[]{
                        venda.getId(),
                        venda.getPagamentoForma(),
                        venda.getSubtotalSoma(),
                        venda.getValorTotal(),
                        venda.getDias()
                });
            } 
        } catch (ConexaoException ex) {
            Logger.getLogger(VendaBuscarData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pesquisarBtActionPerformed

    private void abrirJanela(JFrame jframe){
//        double x = this.getLocationOnScreen().getX();
//        double y = this.getLocationOnScreen().getY();
//        double dx = this.getSize().getWidth();
//        double dy = this.getSize().getHeight();
//        double xx = x + (dx / 2);
//        double yy = y + (dy / 2);
//        double dxx = jframe.getSize().getWidth() / 2;
//        double dyy = jframe.getSize().getHeight() / 2;
//        
//        jframe.setLocation(new Point((int) xx - (int) dxx, (int) yy - (int) dyy));
        
        jframe.setLocationRelativeTo(null);
        jframe.setVisible(true);
        jframe.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    private void vendaTblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendaTblMousePressed
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            try{
                int linhaSlc = vendaTbl.getSelectedRow();

                abrirJanela(new VendaDetalhesJanela(this, gerenciador, vendas.get(linhaSlc)));
                
            } catch (ConexaoException ex) {
                Logger.getLogger(DepositoPainel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_vendaTblMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dataFinalJCld;
    private com.toedter.calendar.JDateChooser dataInicioJCld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pesquisarBt;
    private javax.swing.JTable vendaTbl;
    // End of variables declaration//GEN-END:variables
}
