/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import conexao.ConexaoException;
import manager.Gerenciador;
import entity.Cliente;
import entity.DepositoProduto;
import entity.Produto;
import entity.VendaProduto;
import exception.ExcecaoComposta;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class VendaPainel extends javax.swing.JPanel {
    Gerenciador gerenciador;
    /**
     * Creates new form Venda
     */
    public VendaPainel(Gerenciador gerenciador) throws ConexaoException {
        initComponents();
        
        this.gerenciador = gerenciador;
        
        gerenciador.vendaIniciar();
        
        List<Cliente> clientes = gerenciador.clientesBuscarTodos();
        for(Cliente cliente : clientes){
            clienteCmbBx.addItem(cliente);
        }
        
        List<Produto> produtos = gerenciador.produtosBuscarTodos();
        for(Produto produto : produtos){
            produtoCmbBx.addItem(produto);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        adicionarProdutoBt = new javax.swing.JButton();
        produtoCmbBx = new javax.swing.JComboBox<>();
        quantidadeSpn = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        clienteCmbBx = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        vendaProdutoTbl = new javax.swing.JTable();
        subtotalTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalTxt = new javax.swing.JTextField();
        calcularBt = new javax.swing.JButton();
        finalizaVendaBt = new javax.swing.JButton();
        aVistaBt = new javax.swing.JRadioButton();
        aPrazoBt = new javax.swing.JRadioButton();
        diasTxtFld = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        adicionarProdutoBt.setText("Adicionar");
        adicionarProdutoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarProdutoBtActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantidade:");

        jLabel2.setText("Produto: ");

        jLabel3.setText("Cliente: ");

        vendaProdutoTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Preço atual", "Quantidade", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vendaProdutoTbl);

        jLabel4.setText("Subtotal soma: ");

        jLabel5.setText("Total: ");

        calcularBt.setText("Calcular");
        calcularBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBtActionPerformed(evt);
            }
        });

        finalizaVendaBt.setText("Finalizar venda");
        finalizaVendaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizaVendaBtActionPerformed(evt);
            }
        });

        buttonGroup1.add(aVistaBt);
        aVistaBt.setText("A vista");

        buttonGroup1.add(aPrazoBt);
        aPrazoBt.setText("A prazo");

        jLabel6.setText("Dias: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(calcularBt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(subtotalTxt)
                                .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(aVistaBt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(aPrazoBt)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(diasTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                                    .addComponent(finalizaVendaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(clienteCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(produtoCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(quantidadeSpn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(adicionarProdutoBt)))))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clienteCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarProdutoBt)
                    .addComponent(produtoCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantidadeSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diasTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(subtotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(aVistaBt)
                                .addComponent(aPrazoBt)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalizaVendaBt)))
                    .addComponent(calcularBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarProdutoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarProdutoBtActionPerformed
        // TODO add your handling code here:
        Produto produto = (Produto) produtoCmbBx.getSelectedItem();
        int quantidade = (Integer) quantidadeSpn.getValue();
        gerenciador.vendaAddVendaProduto(produto, quantidade);
        atualizarTabela();
    }//GEN-LAST:event_adicionarProdutoBtActionPerformed

    private void calcularBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBtActionPerformed
        // TODO add your handling code here:
        gerenciador.vendaNovaSetCliente((Cliente) clienteCmbBx.getSelectedItem());
        gerenciador.vendaNovaSetData(new Date());
        gerenciador.vendaNovaSetDias(Integer.parseInt(diasTxtFld.getText()));
        if(aVistaBt.isSelected()){
            gerenciador.vendaNovaSetPagamentoForma("avista");
        }else{
            gerenciador.vendaNovaSetPagamentoForma("aprazo");
        }
        gerenciador.vendaNovaCalcular();
        subtotalTxt.setText(Double.toString(gerenciador.vendaNovaGetSubtotal()));
        totalTxt.setText(Double.toString(gerenciador.vendaNovaGetTotal()));
        
    }//GEN-LAST:event_calcularBtActionPerformed

    private void finalizaVendaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizaVendaBtActionPerformed
        try {
            // TODO add your handling code here:
            gerenciador.vendaFinalizar();
        } catch (ConexaoException ex) {
            Logger.getLogger(VendaPainel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_finalizaVendaBtActionPerformed

    private void atualizarTabela(){
        DefaultTableModel model = (DefaultTableModel) vendaProdutoTbl.getModel();
        model.setRowCount(0);
 
        for(VendaProduto vendaProduto : gerenciador.getVendaNovaVendaProdutos()){
            model.addRow(new Object[]{
                    vendaProduto.getProduto().getNome(),
                    vendaProduto.getProduto().getPrecoAtual(),
                    vendaProduto.getQuantidade(),
                    vendaProduto.getQuantidade() * vendaProduto.getProduto().getPrecoAtual()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aPrazoBt;
    private javax.swing.JRadioButton aVistaBt;
    private javax.swing.JButton adicionarProdutoBt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcularBt;
    private javax.swing.JComboBox<Cliente> clienteCmbBx;
    private javax.swing.JTextField diasTxtFld;
    private javax.swing.JButton finalizaVendaBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Produto> produtoCmbBx;
    private javax.swing.JSpinner quantidadeSpn;
    private javax.swing.JTextField subtotalTxt;
    private javax.swing.JTextField totalTxt;
    private javax.swing.JTable vendaProdutoTbl;
    // End of variables declaration//GEN-END:variables
}
